INSERT INTO autor 
(nacionalidade, nome) values
('BR', 'Mário de Andrade'),
('AT', 'Joseph Roth'),
('US', 'Ava Dellaira'),
('GB', 'Virginia Macgregor'),
('DE', 'Günter Grass'),
('BR', 'Maria Christina Lins do Rego'),
('GB', 'Cara Delevigne'),
('BR', 'Mário Kuperman'),
('US', 'Tilar J. Mazzeo'),
('PT', 'Lídia Jorge'),
('US', 'Emma Cline'),
('BR', 'Nelson Rodrigues'),
('BR', 'Ademir Assunção'),
('BR', 'Milton Hatoum'),
('BR', 'Frei Betto'),
('BR', 'Rubens Figueiredo'),
('BR', 'Rubem Fonseca'),
('US', 'Nora Roberts'),
('BR', 'Gonçalves Dias'),
('FR', 'Christine Féret-Fleury'),
('SE', 'David Lagercrantz'),
('JP', 'Yasunari Kawabata'),
('US', 'Jennifer Egan'),
('BR', 'Saturnino Braga'),
('NO', 'Anne Holt'),
('GB', 'Matt Haig'),
('AT', 'Stefan Zweig'),
('BR', 'Marçal Aquino'),
('HU', 'Ferenc Molnár'),
('BR', 'Rubem Braga'),
('US', 'Andre Aciman'),
('FR', 'Antoine Laurain'),
('US', 'Amy Thomas'),
('US', 'V. S. Alexander'),
('BR', 'Marcio Pitliuk'),
('BR', 'Marcelo Vincintin'),
('CA', 'Denis Thériault'),
('DE', 'Nina George'),
('BR', 'Lygia Fagundes Telles'),
('US', 'Susan Wiggs');

