INSERT INTO categoria 
(nome) values
('Escritores alemães - Biografia'),
('Conto brasileiro'),
('Romance inglês'),
('Guerra Mundial'),
('Literatura portuguesa'),
('Romance americano'),
('Crônica brasileira'),
('Ficção brasileira'),
('Dramaturgos brasileiros'),
('Romance brasileiro'),
('Ficção inglesa'),
('Teatro brasileiro'),
('Ficção francesa'),
('Ficção sueca'),
('Conto japonês'),
('Romance norueguês'),
('Novela austríaca'),
('Romance francês'),
('Literatura infantojuvenil'),
('Romance norte-americano'),
('Romance austríaco'),
('Jornalismo cultural'),
('Ficção americana'),
('Romance alemão'),
('Romance canadense');